services:
  auth-db:
    image: mysql:8
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - auth_db_data:/var/lib/mysql

  user-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5480:5432'
    volumes:
      - user_db_data:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'
    volumes:
      - ./redis.acl:/usr/local/etc/redis/users.acl
    command: >
      redis-server
      --appendonly yes
      --aclfile /usr/local/etc/redis/users.acl

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - '5680:5672'
      - '15672:15672' # dashboard

volumes:
  auth_db_data:
  user_db_data:
